 # Generated by Django 2.2.2 on 2019-06-20 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_title', models.CharField(max_length=20)),
                ('b_pub_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='HeroInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h_name', models.CharField(max_length=10)),
                ('h_gender', models.BooleanField()),
                ('h_content', models.CharField(max_length=1000)),
                ('h_book', models.ForeignKey(on_delete=True, to='booktest.BookInfo')),
            ],
        ),
    ]
