# Generated by Django 2.2.2 on 2019-06-26 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinfo',
            name='b_pub_date',
            field=models.DateTimeField(),
        ),
    ]
